#!/bin/bash

PWD=$(pwd)

source .env
source lib/check_manager
source lib/runner_helper

# main config
PORT=80
JWT=true
JWT_SECRET=secret
JWT_HEADER=Authorization
NAME=ds

_remove_logs $PWD/DocumentServer

docker run  -itd \
            -p $PORT:80 \
            --name $NAME \
            --env JWT_ENABLED=$JWT \
            --env JWT_SECRET=$JWT_SECRET \
            --env JWT_HEADER=$JWT_HEADER \
            --restart unless-stopped \
            -v $PWD/DocumentServer/logs:/var/log/onlyoffice  \
            -v $PWD/DocumentServer/data:/var/www/onlyoffice/Data  \
            -v $PWD/DocumentServer/lib:/var/lib/onlyoffice \
            -v $PWD/DocumentServer/db:/var/lib/postgresql \
            onlyoffice/4testing-documentserver-ee:$VERSION

_wait_launch $NAME
