#!/bin/bash

source ./lib/runner_helper.sh
source .env

# main config
PORT=80
JWT=true
JWT_SECRET=secret
JWT_HEADER=Authorization

_remove_logs $PWD/DocumentServer

docker run  -itd \
            -p $PORT:80 \
            --name ds \
            --env JWT_ENABLED=$JWT \
            --env JWT_SECRET=$JWT_SECRET \
            --env JWT_HEADER=$JWT_HEADER \
            --restart unless-stopped \
            -v $PWD/DocumentServer/logs:/var/log/onlyoffice  \
            -v $PWD/DocumentServer/data:/var/www/onlyoffice/Data  \
            -v $PWD/DocumentServer/lib:/var/lib/onlyoffice \
            -v $PWD/DocumentServer/db:/var/lib/postgresql \
            onlyoffice/4testing-documentserver-ee:$VERSION

echo 'sleep 80'; sleep 80

bash lib/after.sh $NAME
