#!/bin/bash

source ./lib/runner_helper.sh

ABS_PATH=$(pwd)

_remove_logs $ABS_PATH/DocumentServer

# main config
VERSION=7.3.3.49
PORT=80
JWT_ENABLED=false

docker run  -itd \
            -p $PORT:80 \
            --name ds \
            --env JWT_ENABLED=$JWT_ENABLED \
            --restart unless-stopped \
            -v $ABS_PATH/DocumentServer/logs:/var/log/onlyoffice  \
            -v $ABS_PATH/DocumentServer/data:/var/www/onlyoffice/Data  \
            -v $ABS_PATH/DocumentServer/lib:/var/lib/onlyoffice \
            -v $ABS_PATH/DocumentServer/db:/var/lib/postgresql \
            onlyoffice/4testing-documentserver-ee:$VERSION

sleep 80

# docker exec ds  /var/www/onlyoffice/documentserver/npm/json -f \ 
                # /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
docker exec ds sudo supervisorctl start ds:example
docker exec ds sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
docker exec ds cat /etc/supervisor/conf.d/ds-example.conf | grep autostart


#   /etc/onlyoffice/documentserver/log4js/production.json
# replace the 'WARN' value with 'DEBUG' of the "level" parameter.
#   supervisorctl restart all
