#!/bin/bash

source .env

## main configs
PORT=1000
JWT=false
PRIVATE_IP=true
NAME=ds_jwt_disable

docker run  -itd \
            -p $PORT:80 \
            --env JWT_ENABLED=$JWT \
            --env ALLOW_PRIVATE_IP_ADDRESS=$PRIVATE_IP \
            --restart unless-stopped \
            --name $NAME \
            onlyoffice/4testing-documentserver-ee:$VERSION

sleep 80

# docker exec $NAME  /var/www/onlyoffice/documentserver/npm/json -f \
                # /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
                
docker exec $NAME sudo supervisorctl start ds:example
docker exec $NAME sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
docker exec $NAME cat /etc/supervisor/conf.d/ds-example.conf | grep autostart
