#!/bin/bash

## main configs
PORT=1000
VERSION=7.3.3.50
JWT_ENABLED=false
NAME=ds_jwt_disable


docker run  -itd \
            -p $PORT:80 \
            --env JWT_ENABLED=$JWT_ENABLED \
            --restart unless-stopped \
            --name $NAME \
            onlyoffice/4testing-documentserver-ee:$VERSION

sleep 80

# docker exec $NAME  /var/www/onlyoffice/documentserver/npm/json -f \
                # /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
                
docker exec $NAME sudo supervisorctl start ds:example
docker exec $NAME sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
docker exec $NAME cat /etc/supervisor/conf.d/ds-example.conf | grep autostart
