#!/bin/bash

source .env

## main configs
PORT=1000
BRANCH=ee
JWT_ENABLED=false
NAME=lic

PWD=$(pwd)

docker run  -itd \
            -p $PORT:80 \
            -v $PWD/license:/var/www/onlyoffice/Data \
            --env JWT_ENABLED=$JWT_ENABLED \
            --restart unless-stopped \
            --name $NAME \
            onlyoffice/4testing-documentserver-$BRANCH:$VERSION

sleep 80

# docker exec $NAME  /var/www/onlyoffice/documentserver/npm/json -f \
                # /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
                
docker exec $NAME sudo supervisorctl start ds:example
docker exec $NAME sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
docker exec $NAME cat /etc/supervisor/conf.d/ds-example.conf | grep autostart

#   /etc/onlyoffice/documentserver/log4js/production.json
# replace the 'WARN' value with 'DEBUG' of the "level" parameter.
#   supervisorctl restart all
