#!/bin/bash

source ./lib/runner_helper.sh

_remove_logs

ABS_PATH=$(pwd)

# main config
VERSION=7.3.0.104
PORT=80
JWT_ENABLED=false

docker run  -itd \
            -p $PORT:80 \
            --name ds \
            --env JWT_ENABLED=$JWT_ENABLED \
            --restart unless-stopped \
            -v $ABS_PATH/DocumentServer/logs:/var/log/onlyoffice  \
            -v $ABS_PATH/DocumentServer/data:/var/www/onlyoffice/Data  \
            -v $ABS_PATH/DocumentServer/lib:/var/lib/onlyoffice \
            -v $ABS_PATH/DocumentServer/db:/var/lib/postgresql \
            onlyoffice/4testing-documentserver-ee:$VERSION

sleep 120

# docker exec ds  /var/www/onlyoffice/documentserver/npm/json -f \ 
                # /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
docker exec ds sudo supervisorctl start ds:example
docker exec ds sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
docker exec ds cat /etc/supervisor/conf.d/ds-example.conf | grep autostart
