#!/bin/bash

## main configs
PORT=1000
VERSION=7.3.3.11
BRANCH=ee
JWT_ENABLED=false

PWD=$(pwd)

docker run  -itd \
            -p $PORT:80 \
            -v $PWD/license:/var/www/onlyoffice/Data \
            --env JWT_ENABLED=$JWT_ENABLED \
            --restart unless-stopped \
            --name ds_lic \
            onlyoffice/4testing-documentserver-$BRANCH:$VERSION

sleep 80

# docker exec ds_lic  /var/www/onlyoffice/documentserver/npm/json -f \
                # /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
                
docker exec ds_lic sudo supervisorctl start ds:example
docker exec ds_lic sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
docker exec ds_lic cat /etc/supervisor/conf.d/ds-example.conf | grep autostart

#   /etc/onlyoffice/documentserver/log4js/production.json
# replace the 'WARN' value with 'DEBUG' of the "level" parameter.
#   supervisorctl restart all
