#!/bin/bash

TOOLS=/var/www/onlyoffice/documentserver/server/tools
SCRIPT=/usr/bin/documentserver-pluginsmanager.sh
SDKJS_PLUGINS=/var/www/onlyoffice/documentserver/sdkjs-plugins
PM=pluginsmanager

_pm_install() {
    docker exec "$1" cat $SDKJS_PLUGINS/plugin-list-default.json; printf "\n"
    docker exec "$1" $SCRIPT --install=$SDKJS_PLUGINS/plugin-list-default.json
}
